### ISSUE TITLE
Update data author and contributor information

### ISSUE THREAD

**Issue by mianzg** [openwashdata/breathablepitlat#1]
Hi, the current data package include you and our package developer as the authors.

Please provide all other data authors/contributors for this dataset if you are aware of with the format:

First Name:
Family Name:
Email:
ORCiD (if available):

**Comment by larnsce** [comment]
Thanks @yashdubey132 for completing this. I have now build the site. The steps you can follow are:

1. Run the `data_processing.R` script in `data-raw`
2. Run `devtools::build_readme()` in the Console -> that updates the README.md
3. Run `devtools::document()`. Always good to do.
3. Run `devtools::check()`in the Console -> always worthwhile to do a check
4. Run `pkgdown::build_site()` in the Console -> this builds the website that you will eventually have to showcase your curated work. It's the final product and the core value of doing this way, because it will be visually appealing to others in addition to you being able to share certain R analysis you have done with this data (e.g. a key plot from a paper).

**Comment by larnsce** [comment]
@yashdubey132, I see now that this also a function of `washr` and documented here:

https://global-health-engineering.github.io/ghedatapublishing/data_publication.html#setting-up-the-package-website

**Comment by yashdubey132** [comment]
Noted, thank you!
